services:
  iotpilot:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: iotpilot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Using named volume for node_modules to avoid it being overwritten
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./app/public:/usr/src/app/public
      - ./app/config:/usr/src/app/config
    expose:
      - 4000
    networks:
      - web

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=${DOMAIN}  # Use the domain from .env
      - VALIDATION=http  # Changed from dns to http for easier setup
      - SUBDOMAINS=
      - EMAIL=${EMAIL}  # Use the email from .env
    volumes:
      - ./Docker/Swag/nginx-site-confs-default.conf:/config/nginx/site-confs/default.conf
      - ./swag/config:/config
    ports:  # Expose ports to host
      - 80:80
      - 443:443
    depends_on:
      - iotpilot
    restart: unless-stopped
    networks:
      - web

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    privileged: true
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_HOSTNAME=iotpilot
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-routes=172.18.0.0/16
    volumes:
      - ./tailscale-data:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    # Enable access to host network
    network_mode: "host"

networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  node_modules: